### ISSUE TITLE
Doesn't work on Rasperry Pi 3

### ISSUE THREAD

**Issue by Xeoneid** [ujc/wait-for-stuff#1]
I've been using the module on my computer (Windows 10 Intel x86) and it worked fine. But when I deployed it to a Rasperry Pi 3 requiring this module makes it crash with the following exception:
`Unhandled exception at line 234, column 9 in Unknown script code (1)
0x800a1624 - JavaScript runtime error: Reflect.apply: argument is not an array or array-like object`

The code part its breaking on (which is somewhere in a module):
`
var currentStackTrace;
function ensureStackTrace() {
  if (!currentStackTrace) {
    currentStackTrace = parseStack(
      Reflect_apply(oldStackDesc.get, e) || '', // Call saved old getter
      skipDepth, startFuncName);
  }
      return currentStackTrace;
}
`

The code is running in a BasicNodejsWebserver template from VisualStudio (a UWP app that runs node code). The Rasperry Pi is running Windows 10 IoT with Node v7.0.0

**Comment by uri-chandler** [comment]
Seems like it's coming from a different module, and not directly related to "wait-for-stuff".

That said - can you maybe share more details on the error:
1. The full error callstack
2. The code that you're running that triggers this error

I might be able to figure out why this is happening (and maybe even apply a fix in "wait-for-stuff").

*sidenote: if you can use a newer version of node, you're probably better off using "await\async" directly

Thx!

**Comment by Xeoneid** [comment]
Maybe it has to do with Windows IoT itself, I've reached a similar issue in a Microsoft forum but failing with Express.

1.  I couldn't get the full callstack 😞 I swear I'll try again tomorrow.
2.  Believe it or not, the program crashes when use `const wait = require('wait-for-stuff');` I don't even need to call it to make it happen.

**Comment by Xeoneid** [comment]
As I promised: Here is the callstack:
`
TypeError: Reflect.apply: argument is not an array or array-like object
   at ensureStackTrace (Unknown script code:234:9)
   at stackGetter (Unknown script code:244:9)
   at getFileName (C:\Data\Users\DefaultAccount\AppData\Local\Packages\NodejsWebServer1_9bmdm54xz1gf2\LocalState\node_modules\bindings\bindings.js:127:3)
   at bindings (C:\Data\Users\DefaultAccount\AppData\Local\Packages\NodejsWebServer1_9bmdm54xz1gf2\LocalState\node_modules\bindings\bindings.js:55:5)
   at Anonymous function (C:\Data\Users\DefaultAccount\AppData\Local\Packages\NodejsWebServer1_9bmdm54xz1gf2\LocalState\node_modules\deasync\index.js:34:3)
   at Anonymous function (C:\Data\Users\DefaultAccount\AppData\Local\Packages\NodejsWebServer1_9bmdm54xz1gf2\LocalState\node_modules\deasync\index.js:9:2)
   at Module.prototype._compile (module.js:560:3)
   at Module._extensions[.js] (module.js:569:3)
   at Module.prototype.load (module.js:477:3)
   at tryModuleLoad (module.js:436:5)
`

**Comment by uri-chandler** [comment]
Closing this for now, as I don't have a Raspberry Pi 3 available for testing this further.
Please do open a new issue if you think there's anything else I can assist with on this.

**Comment by Xeoneid** [comment]
Don't worry. I don't even work on that project anymore
