### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by Mambix** [ujc/wait-for-stuff#3]
When I run my code on windows machine I get this Unexpected token error:

```
PS D:\GIT\MVM\node.api> node index.js
D:\GIT\MVM\node.api\node_modules\wait-for-stuff\index.js:48
    use: function use(...args) {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\GIT\MVM\node.api\modules\printeebook.js:4:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

I can run my code on my lubuntu 18.04 laptop with out any issues. Any idea what is going on?

```JSON
"dependencies": {
    "exif": "^0.6.0",
    "express": "^4.16.3",
    "firebase-admin": "^5.12.0",
    "pdfkit": "^0.8.3",
    "wait-for-stuff": "^1.4.0"
  }
```

**Comment by uri-chandler** [comment]
What NodeJS version are you using?
Sounds like it might be a NodeJS version that doesn't support the Rest operator.

**Comment by Mambix** [comment]
was version 4.0.0
upgraded to latest and it's working now

**Comment by uri-chandler** [comment]
Awesome.
